# Generated by Django 5.0.2 on 2024-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_rename_thumbnail_info_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="profile-image/"),
        ),
    ]
