# Generated by Django 5.0.2 on 2024-05-06 14:33

from django.db import migrations, models

import blog.storage


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_alter_info_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=blog.storage.Cafe24OBS,
                upload_to="profile-image/",
            ),
        ),
    ]
