# Generated by Django 5.0.7 on 2024-08-16 08:28

from django.db import migrations, models

import blog.storage


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_info_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=blog.storage.OBS,
                upload_to="staticfiles/",
            ),
        ),
    ]
