# Generated by Django 5.0.7 on 2024-08-21 10:52

from django.db import migrations, models

import blog.storage


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                editable=False,
                storage=blog.storage.OBS,
                unique=True,
                upload_to="media/",
            ),
        ),
    ]
