# Generated by Django 5.0.7 on 2024-08-29 07:27

import blog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_alter_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                editable=False,
                height_field="height",
                storage=blog.storage.Cafe24OBS,
                unique=True,
                upload_to="media/",
                width_field="width",
            ),
        ),
    ]
