# Generated by Django 5.0.2 on 2024-03-17 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'],
                     'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
