# Generated by Django 5.0.2 on 2024-05-10 15:07

from django.db import migrations, models

import blog.storage


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_category_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=blog.storage.OBS,
                upload_to="category-image/",
            ),
        ),
    ]
