# Generated by Django 5.0.2 on 2024-07-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
