# Generated by Django 5.0.2 on 2024-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_post_text_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="template",
            options={"ordering": ["title"]},
        ),
        migrations.RenameField(
            model_name="template",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
