# Generated by Django 5.0.7 on 2024-08-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_draft_thumbnail_remove_post_thumbnail_and_more"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="thumbnail",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_thumbnail_of",
                to="media.image",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_thumbnail_of",
                to="media.image",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="thumbnail",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_thumbnail_of",
                to="media.image",
            ),
        ),
    ]
