# Generated by Django 5.0.7 on 2024-09-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_template_options_template_template_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="draft",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="draft",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
