# Generated by Django 5.1.2 on 2024-10-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_draft_tags_post_tags_template_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="draft",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="template",
            name="tags",
        ),
        migrations.AddField(
            model_name="draft",
            name="tags",
            field=models.ManyToManyField(
                related_name="tagged_%(class)s", to="core.hashtag"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                related_name="tagged_%(class)s", to="core.hashtag"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="tags",
            field=models.ManyToManyField(
                related_name="tagged_%(class)s", to="core.hashtag"
            ),
        ),
    ]
