# Generated by Django 5.1.2 on 2024-10-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_hashtag_remove_draft_tags_remove_post_tags_and_more"),
        ("media", "0003_image_height_image_width_alter_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_content_of", to="media.image"
            ),
        ),
        migrations.AlterField(
            model_name="draft",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="core.hashtag"
            ),
        ),
        migrations.AlterField(
            model_name="draft",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_thumbnail_of",
                to="media.image",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_content_of", to="media.image"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="core.hashtag"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_thumbnail_of",
                to="media.image",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_content_of", to="media.image"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="core.hashtag"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_thumbnail_of",
                to="media.image",
            ),
        ),
    ]
