# Generated by Django 5.0.7 on 2024-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_draft_images_alter_draft_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hashtag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="draft",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)ss", to="core.hashtag"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)ss", to="core.hashtag"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)ss", to="core.hashtag"
            ),
        ),
    ]
