# Generated by Django 5.0.2 on 2024-05-11 08:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_category_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
    ]
