name: Build release

on:
  release:
    types:
      - created
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.brighteast.me
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          docker build \
          -t docker.brighteast.me/services/blog:${RELEASE_TAG} \
          --build-arg DJANGO_SECRET_KEY="$DJANGO_SECRET_KEY" \
          .
          docker push docker.brighteast.me/services/blog:${RELEASE_TAG}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image service/blog container-0=docker.brighteast.me/services/blog:${RELEASE_TAG} --namespace=service
          kubectl rollout status service/blog --namespace=service

      - name: Notify release
        run: |
          curl -X POST "https://n8n.brighteast.me/webhook/notification" \
          -u ${{ secrets.WEBHOOK_BASIC_AUTH }} \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"🔔 **${{ github.event.repository.name }}** ${RELEASE_TAG} 배포 완료\"}"

      - name: Notify on Failure
        if: failure()
        run: |
          curl -X POST "https://n8n.brighteast.me/webhook/notification" \
          -u ${{ secrets.WEBHOOK_BASIC_AUTH }} \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"🚨 **${{ github.event.repository.name }}** ${RELEASE_TAG} 배포 실패\"}"
