name: Build latest

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Registryz
        uses: docker/login-action@v2
        with:
          registry: docker.brighteast.me
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build project
        run: |
          docker build -t docker.brighteast.me/blog/blog:latest \
          --build-arg DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
          .
          docker push docker.brighteast.me/blog/blog:latest
