name: Build latest

on:
  release:
    types:
      - created

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.brighteast.me
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          docker build \
          -t docker.brighteast.me/services/blog:${RELEASE_TAG} \
          --build-arg DJANGO_SECRET_KEY="$DJANGO_SECRET_KEY" \
          .
          docker push docker.brighteast.me/services/blog:${RELEASE_TAG}
