name: Build release

on:
  release:
    types:
      - created

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      RELEASE_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.brighteast.me
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          docker build \
          -t docker.brighteast.me/services/blog:${RELEASE_TAG} \
          --build-arg DJANGO_SECRET_KEY="$DJANGO_SECRET_KEY" \
          .
          docker push docker.brighteast.me/services/blog:${RELEASE_TAG}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/blog container-0=docker.brighteast.me/services/blog:${RELEASE_TAG} --namespace=service
          kubectl rollout status deployment/blog --namespace=service

  notify-success:
    needs: build-and-release
    if: needs.build-and-release.result == 'success'
    uses: brighteast99/workflows/.github/workflows/notify.yaml@main
    with:
      target: discord
      identity: github
      message: '🔔 **${{ github.event.repository.name }}** ${RELEASE_TAG} 릴리즈 완료'
    secrets:
      auth: ${{ secrets.WEBHOOK_BASIC_AUTH }}

  notify-failure:
    needs: build-and-release
    if: needs.build-and-release.result == 'failure'
    uses: brighteast99/workflows/.github/workflows/notify.yaml@main
    with:
      target: discord
      identity: github
      message: '🚨 **${{ github.event.repository.name }}** ${RELEASE_TAG} 릴리즈 실패'
    secrets:
      auth: ${{ secrets.WEBHOOK_BASIC_AUTH }}
